config/routes.rb
require 'sidekiq/web'
require Rails.root.join('lib', 'subdomain.rb')

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  get "debug" => "sessions#debug", :as => "debug"
  namespace :admin do
    resources :users, only: [:index, :new, :create]
  end

  constraints Subdomain do # サブドメインが指定されていた場合に以下のルーティングが利用される
    namespace :settings do
      root to: "base#index"
    end
  end
  root to:  'client#launch'

  # Todo ローンチする前にurlをかえる

  # for api
  use_doorkeeper
  namespace :api, defaults: {format: 'json'} do
    # private api
    scope 'p', module: 'private' do
      resources :users, only: [:index]
      resources :articles, except: [:destroy, :edit] do
        collection do
          get 'tags'
          post 'upload_image'
          post 'upload_image_url'
          post 'upload_crop_image'
        end
      end
      post "/log/:event" => "log#event"
    end

    # public api
    scope ':versions', module: 'versions' do
      resources :users, except: [:new, :edit, :update]
    end
  end

  scope 'twilio', module: 'twilio' do
    resources :task_router, only: [] do
      collection do
        get :agent
        post :workflow
        post :assignment
      end
    end
  end
  resources :twilio, only: [] do
    collection do
      post :incoming
      post :outgoing
      post :collect_digit
      post :queue
      post :enqueue
      post :wait_enqueue
    end
  end
  # get '/:id', to: 'articles#show', constraints: { id: /\d+/ }, as: 'article'
  # get "hashtag/:name" => "articles#tag"

  resources :client_test
  # create newはadminで作る
  resources :users, only: [:index, :show]
  # resources :users, only: [:index, :show, :create, :new]
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :demo_first_user
      get :demo_second_user
      get :demo_third_user
    end
  end
  resources :articles, only: [:index, :show]
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "twitter_login" => "sessions#twitter_login"
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get "/signup" => "sessions#signup"
  post '/sessions', :to => 'sessions#callback'
  resources :sessions do
    collection do
      post 'create_acount'
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Errors
  # 左から下書き、公開、完成してるけどまだ公開しない、完成済み
  enum status: [:draft, :publish, :future, :completion, :without_image]

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true

  belongs_to :user
  belongs_to :category
  has_and_belongs_to_many :lists
  acts_as_taggable

  scope :until_idea, -> { where(user_id: nil) }

  scope :entertainment, -> {
    includes(:category).where(categories: {name: "エンターテイメント"})
  }
  scope :culture, -> {
    includes(:category).where(categories: {name: "カルチャー"})
  }
  scope :topic, -> {
    includes(:category).where(categories: {name: "話題"})
  }
  scope :lifestyle, -> {
    includes(:category).where(categories: {name: "ライフスタイル"})
  }
  scope :quiz, -> {
    includes(:theme).where(themes: {name: "クイズ"})
  }

  scope :filter_user, -> (user_id) { where(user_id: user_id) }

  def can_read_user?(user)
    # 公開記事
    return true if self.publish?
    # ログインしていない
    return false if user.nil?

    if user.admin? || user.editor?
      return true
    elsif user.writer?
      if self.user == user
        return true
      # 記事案ならみれる
      elsif self.user.nil?
        return true
      else
        return false
      end
    else
      return false
    end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < BaseController
    authorize_resource only: [:index, :user, :publish, :completion, :future, :draft, :new, :create, :without_image]
    load_and_authorize_resource only: [:show, :edit, :update, :destroy, :to_completion, :reservation_post, :to_idea, :to_without_image]

    respond_to :html

    def index
      @articles = Article.all
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      respond_with(@articles)
    end

    def attentions
      @article = Article.new
      @articles = Article.where(attention: true)
        .order(updated_at: :desc)
        .page(params[:page])
      respond_with(@articles)
    end

    def add_attention
      article = Article.find_by(id: params[:article][:id])
      article.update(attention: true)
      redirect_to :back
    end

    def delete_attention
      article = Article.find_by(id: params[:id])
      article.update(attention: false)
      redirect_to :back
    end

    def show
      respond_with(@article)
    end

    def user
      if params[:user_id].present?
        user_id = params[:user_id]
      else
        user_id = current_user.id
      end

      @articles = Article
        .filter_user(user_id)
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      render :index
    end

    def publish
      @articles = Article
        .publish
        .eager_load(:user)
        .eager_load(:theme)
        .order(published_at: :desc)
        .page(params[:page])
      render :index
    end

    def draft
      @articles = Article
        .draft
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      render :index
    end

    def future
      @articles = Article
        .future
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      render :index
    end

    def completion
      @articles = Article
        .completion
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      render :index
    end

    def without_image
      @articles = Article
        .without_image
        .eager_load(:user)
        .eager_load(:theme)
        .order(updated_at: :desc)
        .page(params[:page])
      render :index
    end

    def new
      @article = Article.new
      respond_with(@article)
    end

    def edit
    end

    def to_completion
      @article.completion!
      redirect_to :back
    end

    def to_idea
      @article.draft!
      @article.update(user_id: nil)
      redirect_to :back
    end

    def to_without_image
      @article.without_image!
      @article.update(user_id: nil)
      redirect_to :back
    end

    def reservation_post
      # Todo 実装する
      raise
      # redirect_to :back
    end

    def create
      @article = Article.new(article_params)
      @article.save
      respond_with(@article)
    end

    def update
      @article.update(article_params)
      respond_with(@article)
    end

    def destroy
      @article.destroy
      respond_with(@article)
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :main_image, :sub_url, :theme_id, :status, :user_id, contents: [:text, :type, :image, :src])
    end
  end
end

app/controllers/api/private/articles_controller.rb
# sample api
module Api::Private
  class ArticlesController < BaseController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    respond_to :json

    def index
      @articles = Article.includes(:category)
        .publish
        .order(published_at: :desc)
        .page(params[:page])
        .per(6)
    end

    def show
      respond_with(@article)
    end

    def new
      @article = Article.new
      respond_with(@article)
    end

    def create
      @article = Article.new(article_params)
      @article.user = current_user
      params[:tag_list] ? @article.tag_list = params[:tag_list].map{|tag| tag[:text]} : @article.tag_list = []
      params[:references] ? @article.references = params[:references].map{|tag| tag[:text]} : @article.references = []
      @article.save
      respond_with(@article)
    end

    def update
      @article.user = current_user if @article.user && @article.user.writer?
      params[:tag_list] ? @article.tag_list = params[:tag_list].map{|tag| tag[:text]} : @article.tag_list = []
      params[:references] ? @article.references = params[:references].map{|tag| tag[:text]} : @article.references = []
      @article.update(article_params)
      notify_to_slack(@article.user, @article) if @article.user && @article.user.writer?
      respond_with(@article)
    end

    def tags
      @tags = Article.tags_on(:tags).where("name LIKE ?", "%#{params[:query]}%")
    end

    # imageをupload
    # Todo ファイル名を変更
    def upload_image
      file = params[:file]
      thumb = Magick::Image.from_blob(file.read).shift
      thumb_out = thumb.to_blob
      path = "images/contents/" + rand(36**10).to_s(36) + ".png"
      s3 = Aws::S3::Client.new
      s3.put_object(
        bucket: Rails.application.secrets.aws_bucket,
        # body: file.tempfile,
        body: thumb_out,
        key: path,
        acl: 'public-read'
      )
      @image = 'https://s3-ap-northeast-1.amazonaws.com/' + Rails.application.secrets.aws_bucket + '/' + path
    end

    def upload_image_url
      file = Magick::Image.read(params[:url])[0]
      thumb_out = file.to_blob
      path = "images/contents/" + rand(36**10).to_s(36) + ".png"
      s3 = Aws::S3::Client.new
      s3.put_object(
        bucket: Rails.application.secrets.aws_bucket,
        # body: file.tempfile,
        body: thumb_out,
        key: path,
        acl: 'public-read'
      )
      @image = 'https://s3-ap-northeast-1.amazonaws.com/' + Rails.application.secrets.aws_bucket + '/' + path
      render "upload_image"
    end

    # リサイズしたimageをupload
    # Todo ファイル名を変更
    def upload_crop_image
      size = JSON.parse(params[:size_data])
      file = params[:file]
      thumb = Magick::Image.from_blob(file.read).shift
      thumb = thumb.crop(size["x"].to_i, size["y"].to_i, size["width"].to_i, size["height"].to_i)
      thumb = thumb.resize_to_fit(params["width"].to_i, params["height"].to_i)
      thumb_out = thumb.to_blob
      path = "images/main_image/" + rand(36**10).to_s(36) + ".png"
      s3 = Aws::S3::Client.new
      s3.put_object(
        bucket: Rails.application.secrets.aws_bucket,
        # body: file.tempfile,
        body: thumb_out,
        key: path,
        acl: 'public-read'
      )
      @image = 'https://s3-ap-northeast-1.amazonaws.com/' + Rails.application.secrets.aws_bucket + '/' + path
      render "upload_image"
    end

    private

      def notify_to_slack(user, article)
        return unless Rails.env.production?
        text = <<-EOC
        [#{user.name}]様より 新しい記事が投稿されました。

        ▼タイトル
        #{article.title}
        ▼URL
        http://qolony.jp/#{article.id}
        ▼ユーザーさんのメールアドレス
        #{user.email}
         EOC

        Slack.chat_postMessage text: text, username: "美人社長秘書", channel: "#article"
      end

      def set_article
        @article = Article.find(params[:id])
      end

      def article_params
        params.require(:article).permit(
          :title,
          :description,
          :main_image,
          :tag_list,
          :theme_id,
          :category_id,
          :thumbnail_image,
          :sub_url,
          :theme_id,
          :status,
          :user_id,
          contents: [objects: [
            :text,
            :type,
            :image,
            :src,
            :url,
            :start,
            questions: [
              :image,
              :title,
              credit: [:text, :url],
             answer_information: [
               :column_type,
               answers: [
                 :image,
                 :title,
                 :correct,
                 :result_id,
                 credit: [:text, :url]
               ]
             ],
             each_result: [
               :explanation,
               :image,
               credit: [:text, :url]
             ]
            ],
            results: [
              :result_id,
              :title,
              :image,
              :twitter_image,
              :description,
              :to,
              :from,
              credit: [:text, :url]
            ]
          ]])
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @articles = Article.includes(:category)
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder}
      format.json
    end
  end

  def attentions
    @articles = Article.includes(:category)
      .where(attention: true)
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json { render "articles/index" }
    end
  end

  def tag
    @tag = params[:name]
    @articles =Article.tagged_with(@tag)
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder}
      format.json { render "articles/index" }
    end
  end

  def quiz
    @articles = Article.quiz
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json { render "articles/index" }
    end
  end

  def lifestyle
    @articles = Article.lifestyle
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json {render "articles/index"}
    end
  end

  def culture
    @articles = Article.culture
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json {render "articles/index"}
    end
  end

  def entertainment
    @articles = Article.entertainment
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json {render "articles/index"}
    end
  end

  def topic
    @articles = Article.topic
      .publish
      .order(published_at: :desc)
      .page(params[:page])
      .per(6)

    respond_to do |format|
      format.html {gon.jbuilder template: "app/views/articles/index.json.jbuilder"}
      format.json {render "articles/index"}
    end
  end

  def show
    raise NotFoundError unless @article.can_read_user?(current_user)
    gon.jbuilder
    respond_to do |format|
      format.html
      format.json
    end
  end

  def js_show
    @article = Article.find(params[:id])
    gon.jbuilder
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :main_image, :sub_url, :theme_id, :status, :user_id, :name, contents: [:text, :type, :image, :src])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # contentを展開
  def show_content(content)
    case content["type"]
    when "text"
      content_tag(:p, content["text"], class: :content_p)
    when "headline"
      content_tag(:h2, content["text"], class: :content_h2)
    when "reference"
      content_tag(:blockquote, content["text"], class: :content_blockquote)
    when "image"
      image_tag(content["image"], class: :content_img)
    when "youtube"
      youtube_tag(content["src"]).html_safe
    when "script"
      content["src"].html_safe
    when "tirivia"
      content_tag(:div, content["questions"], class: :trivia) #実際の記事表示で必要 show.html.erb
    when "personality"
      content_tag(:div, content["questions"], class: :personality)
    end
  end

  def youtube_tag(src)
    return '<div class="youtube-container"><iframe id="player" type="text/html" width="640" height="390" src=' + src + ' frameborder="0"></iframe></div>'
  end

  def status_button(article)
    if  article.publish?
      return '<span class="label label-primary label-mini btn-round">公開</span>'
    elsif article.future?
      return '<span class="label label-success label-mini btn-round">公開予定</span>'
    elsif article.draft?
      return '<span class="label label-warning label-mini btn-round">下書き</span>'
    elsif article.completion?
      return '<span class="label label-info label-mini btn-round">完成済み</span>'
    end
  end
end

app/views/admin/articles/attentions.html.erb
<div class="row">
  <div class="col-sm-8 articles-page-bar">
    <div class="page_entries_info">
      <%= paginate @articles %>
    </div>
  </div>
  <div class="col-sm-4 articles-page-bar">
    <div class="page_entries_info">
      <div class="article-pager-info">
        <%= page_entries_info @articles %>
      </div>
    </div>
  </div>
</div>

<div class="panel-body">
    <div class="position-left">
      <%= form_for @article, url: add_attention_admin_articles_path, html: {class: "form-horizontal"} do |f| %>
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <div class="col-lg-6">
            <%= f.collection_select :id, Article.all, :id, :title,  {prompt: "記事を追加"}, {class: "form-control"} %>
            <%= f.submit "追加", class: "btn btn-info" %>
          </div>
        </div>
        </div>
    <% end %>
</div>


<!-- page start-->
<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                注目記事一覧(目立たせることができる)
            </header>
            <div class="panel-body">
                <table class="table  table-hover general-table">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>タイトル</th>
                      <th>ステータス</th>
                      <th>公開日</th>
                      <th>削除</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @articles.each do |article| %>
                      <tr>
                          <td><%= article.id %></td>
                          <td><%= article.title %></td>
                          <td><%= article.status %></td>
                          <td><%= article.published_at %></td>
                          <td>
                            <%= link_to delete_attention_admin_article_path(article.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <span class="label label-danger label-mini btn-round">外す</span>
                            <% end %>
                          </td>
                      </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<!-- page end-->

app/views/admin/articles/edit.html.erb
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<div class="row">
  <div class="col-sm-8 articles-page-bar">
    <div class="page_entries_info">
      <%= paginate @articles %>
    </div>
  </div>
  <div class="col-sm-4 articles-page-bar">
    <div class="page_entries_info">
      <div class="article-pager-info">
        <%= page_entries_info @articles %>
      </div>
    </div>
  </div>
</div>


<!-- page start-->
<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                記事一覧
            </header>
            <div class="panel-body">
                <table class="table  table-hover general-table">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>タイトル</th>
                      <th>カテゴリ</th>
                      <% unless current_user.writer? %>
                        <th>ライター</th>
                        <th>ステータス</th>
                      <% end %>
                      <th>プレビュー</th>
                      <% unless current_user.writer? %>
                        <th>画像挿入待ち記事に移動</th>
                      <% end %>
                      <th>編集する</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @articles.each do |article| %>
                      <tr>
                          <td><%= article.id %></td>
                          <td><%= article.title %></td>
                          <td><%= article.try(:category).try(:name) %></td>
                          <% unless current_user.writer? %>
                            <td><%= article.user.email if article.user.present? %></td>
                            <td><%= article.status %></td>
                          <% end %>
                          <td>
                            <%= link_to article do %>
                              <span class="label label-primary label-mini btn-round">プレビュー</span>
                            <% end %>
                          </td>
                          <% unless current_user.writer? %>
                            <td>
                              <%= link_to to_without_image_admin_article_path(article), method: :post do %>
                                <span class="label label-success label-mini btn-round">画像挿入待ち</span>
                              <% end %>
                            </td>
                          <% end %>
                          <td>
                            <%= link_to edit_admin_article_path(article) do %>
                              <span class="label label-info label-mini btn-round">編集</span>
                            <% end %>
                          </td>
                      </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<!-- page end-->

app/views/admin/articles/new.html.erb
<%= render 'form' %>

app/views/admin/articles/show.html.erb
<div id="article-page">
<article class="article">
  <div class="main-image">
    <%= image_tag(@article.main_image) %>
  </div>
  <div class="main">
    <h1>
      <%= @article.title %>
    </h1>
    <div>
      <p>
        <%= simple_format(@article.description) %>
      </p>
    </div>
    <% @article.contents["objects"].each do |content| %>
      <div class="article-content">
        <%= show_content(content) %>
      </div>
    <% end %>
  </div>
</article>
</div>


<div class="article-footer-share-fixed">
  <ul class="c-line share-line" data-tap-list="">
    <li class="share-item">
      <a class="share-btn share-btn-facebook c-btn" id="fb-share" target="_blank">
        <i class="c-ico c-ico--facebookShare-small"></i>
        <span>シェア</span>
      </a>
    </li>
    <li class="share-item">
      <a class="share-btn share-btn-twitter c-btn" href="http://twitter.com/share?url=<%= article_url %>&text=<%= @article.title %>&via=qolony0" target="_blank">
        <i class="c-ico c-ico--twitterShare-small"></i>
        <span>ツイート</span>
      </a>
    </li>
    <li class="share-item">
      <a class="share-btn share-btn-line c-btn" href="http://line.me/R/msg/text/?<%= @article.title + " " + article_url %>">
        <i class="c-ico c-ico--lineShare-small"></i>
        <span>送る</span>
      </a>
    </li>
    <li class="share-item c-line__item share-fb-like">
      <div class="fb-like" data-href="https://www.facebook.com/qolony" data-layout="button" data-action="like" data-show-faces="true" data-share="false"></div>
    </li>
  </ul>
</div>
<div id="fb-root"></div>

<script src='http://connect.facebook.net/ja_JP/all.js'></script>
<script>
  // facebook like button
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&appId=465680123608785&version=v2.3";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  // facebook like ここまで
  // ここからfacebook share (development環境は動かない)
  FB.init({appId: "<%= Rails.application.secrets.fb_app_id %>", status: true, cookie: true});
  // calling the API ...
  $('#fb-share').click(function(e){
    e.preventDefault();
    var obj = {
      method: 'feed',
      // display: 'dialog',
      display: "touch",
      ref: "mobile_share",
      link: document.location.href,
      picture: '<%= @article.main_image %>',
      name: '<%= @article.title %>',
      caption: 'www.qolony.jp',
      description: '<%= @article.description.gsub(/\r\n|\r|\n/, "<br />") %>'
    };
    function callback(response) {
      if(response){
        window.close();
        document.location.href = document.location.href;
      }
    }
    FB.ui(obj, callback);
  });
</script>