config/routes.rb
require 'sidekiq/web'
require Rails.root.join('lib', 'subdomain.rb')

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  get "debug" => "sessions#debug", :as => "debug"
  namespace :admin do
    resources :users, only: [:index, :new, :create]
  end

  constraints Subdomain do # サブドメインが指定されていた場合に以下のルーティングが利用される
    namespace :settings do
      root to: "base#index"
    end
  end
  root to:  'client#launch'

  # Todo ローンチする前にurlをかえる

  # for api
  use_doorkeeper
  namespace :api, defaults: {format: 'json'} do
    # private api
    scope 'p', module: 'private' do
      resources :users, only: [:index]
      resources :articles, except: [:destroy, :edit] do
        collection do
          get 'tags'
          post 'upload_image'
          post 'upload_image_url'
          post 'upload_crop_image'
        end
      end
      post "/log/:event" => "log#event"
    end

    # public api
    scope ':versions', module: 'versions' do
      resources :users, except: [:new, :edit, :update]
    end
  end

  scope 'twilio', module: 'twilio' do
    resources :task_router, only: [] do
      collection do
        get :agent
        post :workflow
        post :assignment
      end
    end
  end
  resources :twilio, only: [] do
    collection do
      post :incoming
      post :outgoing
      post :collect_digit
      post :queue
      post :enqueue
      post :wait_enqueue
    end
  end
  # get '/:id', to: 'articles#show', constraints: { id: /\d+/ }, as: 'article'
  # get "hashtag/:name" => "articles#tag"

  resources :client_test
  # create newはadminで作る
  resources :users, only: [:index, :show]
  # resources :users, only: [:index, :show, :create, :new]
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :demo_first_user
      get :demo_second_user
      get :demo_third_user
    end
  end
  resources :articles, only: [:index, :show]
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "twitter_login" => "sessions#twitter_login"
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get "/signup" => "sessions#signup"
  post '/sessions', :to => 'sessions#callback'
  resources :sessions do
    collection do
      post 'create_acount'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  enum status: [:normal, :writer, :admin, :editor]
  has_many :articles
  has_many :auths
  belongs_to :team
  scope :filter_team, -> (team_id) { where(team_id: team_id) }

  validates :password, length: { minimum: 6 }, unless: proc { |a| a.password.blank? }
  validates :password, confirmation: true, unless: proc { |a| a.password.blank? }
  validates :password_confirmation, presence: true, unless: proc { |a| a.password.blank? }
  validates :email, uniqueness: true, if: proc { |a| a.team.users.exists?(email: a.email) }
  validates :name, uniqueness: true, if: proc { |a| a.name.present? }

  # twilioに登録するIDはハイフンが使えないのでアンダースコアに変換する
  def uid
    uuid.gsub("-", "_") unless uuid.nil?
  end

  # def uuid
  #   return nil if super.nil?
  #   super.gsub("-", "_")
  # end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    authorize_resource
    respond_to :html

    def index
      @users = User
        .all
        .order(updated_at: :desc)
        .page(params[:page])
      respond_with(@users)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        @user.writer!
        redirect_to admin_users_path, notice: "ライターを追加しました!"
      else
        redirect_to :back, notice: @user.errors.full_messages
      end
    end

    private

      def user_params
        params.require(:user).permit(:id, :email, :name, :password, :password_confirmation)
      end
  end
end

app/controllers/api/private/users_controller.rb
module Api::Private
  class UsersController < BaseController
    respond_to :json
    def index
      @users = User.filter_team(current_user.team_id)
    end
  end
end

app/controllers/api/versions/users_controller.rb
# sample api
module Api::Versions
  class UsersController < BaseController
    doorkeeper_for :index, :show, :destroy
    # before_filter :validate_token
    # before_filter :set_parameters
    # skip_before_filter :verify_authenticity_token # allow CSRF

    def index
      # deal with api version 1
      case params[:versions]
      when 'v1'
        render json: current_user
      else
        return head(401)
      end
      # Todo bad request
    end

    def create
      case params[:versions]
      when 'v1'
        @user = User.new(user_params)
      else
        return head(401)
      end

      if @user.save
        render action: 'show', status: :created
      else
        head :bad_request
      end
    end

    def show
      render json: current_user
    end

    def destroy
    end

    private

      def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
      end

    # # def validate_token
    # #   return head(401) unless doorkeeper_token
    # # end
    #
    # def set_parameters
    #   sign_in 'user', User.find(doorkeeper_token.resource_owner_id)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  doorkeeper_for :show

  def index
    render json: "hoge"
  end

  def new
    @user = User.new
  end

  def show
    render json: current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      head :created
      # redirect_to root_url, :notice => "Signed up!"
    else
      head :bad_request
      # render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:id, :email, :password, :password_confirmation)
    end
end

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-sm-8 articles-page-bar">
    <div class="page_entries_info">
      <%= paginate @users %>
    </div>
  </div>
  <div class="col-sm-4 articles-page-bar">
    <div class="page_entries_info">
      <div class="article-pager-info">
        <%= page_entries_info @users %>
      </div>
    </div>
  </div>
</div>

<%= link_to new_admin_user_path do %>
  <button class="btn btn-primary">
    ライターを追加 <i class="fa fa-plus"></i>
  </button></br></br>
<% end %>

<!-- page start-->
<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
              ライター管理
            </header>
            <div class="panel-body">
                <table class="table  table-hover general-table">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>名前</th>
                      <th>メール</th>
                      <th>権限</th>
                      <th>書いた記事リスト</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @users.each do |user| %>
                      <tr>
                          <td><%= user.id %></td>
                          <td><%= user.name %></td>
                          <td><%= user.email %></td>
                          <td><%= user.status %></td>
                          <td>
                            <%= link_to user_admin_articles_path(user_id: user.id) do %>
                              <span class="label label-primary label-mini btn-round">記事一覧</span>
                            <% end %>
                          </td>
                      </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<!-- page end-->

app/views/admin/users/new.html.erb
<div class="row">
<div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
              ライターを追加
            </header>
            <div class="panel-body">
                <div class="position-center">

                  <%= form_for @user, url: admin_users_path, html: {class: "form-horizontal"} do |f| %>
                    <% if @user.errors.any? %>
                      <div id="error_explanation">
                        <ul>
                        <% @user.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="form-group">
                      <label class="control-label">Email</label></br>
                        <div class="col-lg-8">
                            <%= f.text_field :email, class: "form-control" %>
                        </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label">Name</label></br>
                        <div class="col-lg-8">
                            <%= f.text_field :name, class: "form-control" %>
                        </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label">password</label></br>
                        <div class="col-lg-8">
                            <%= f.password_field :password, class: "form-control" %>
                        </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label">確認のためpasswordをもう一度入力</label></br>
                        <div class="col-lg-8">
                            <%= f.password_field :password_confirmation, class: "form-control" %>
                        </div>
                    </div>


                    <%= f.submit "Submit", class: "btn btn-info" %>
                  <% end %>
                </div>

            </div>
        </section>
        </div>
</div>