config/routes.rb
require 'sidekiq/web'
require Rails.root.join('lib', 'subdomain.rb')

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  get "debug" => "sessions#debug", :as => "debug"
  namespace :admin do
    resources :users, only: [:index, :new, :create]
  end

  constraints Subdomain do # サブドメインが指定されていた場合に以下のルーティングが利用される
    namespace :settings do
      root to: "base#index"
    end
  end
  root to:  'client#launch'

  # Todo ローンチする前にurlをかえる

  # for api
  use_doorkeeper
  namespace :api, defaults: {format: 'json'} do
    # private api
    scope 'p', module: 'private' do
      resources :users, only: [:index]
      resources :articles, except: [:destroy, :edit] do
        collection do
          get 'tags'
          post 'upload_image'
          post 'upload_image_url'
          post 'upload_crop_image'
        end
      end
      post "/log/:event" => "log#event"
    end

    # public api
    scope ':versions', module: 'versions' do
      resources :users, except: [:new, :edit, :update]
    end
  end

  scope 'twilio', module: 'twilio' do
    resources :task_router, only: [] do
      collection do
        get :agent
        post :workflow
        post :assignment
      end
    end
  end
  resources :twilio, only: [] do
    collection do
      post :incoming
      post :outgoing
      post :collect_digit
      post :queue
      post :enqueue
      post :wait_enqueue
    end
  end
  # get '/:id', to: 'articles#show', constraints: { id: /\d+/ }, as: 'article'
  # get "hashtag/:name" => "articles#tag"

  resources :client_test
  # create newはadminで作る
  resources :users, only: [:index, :show]
  # resources :users, only: [:index, :show, :create, :new]
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :demo_first_user
      get :demo_second_user
      get :demo_third_user
    end
  end
  resources :articles, only: [:index, :show]
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "twitter_login" => "sessions#twitter_login"
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get "/signup" => "sessions#signup"
  post '/sessions', :to => 'sessions#callback'
  resources :sessions do
    collection do
      post 'create_acount'
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html ng-app ="qolony">
<head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="keywords" content="QOLONY, コロニー, qolony, クイズ, 診断, キュレーション, まとめ, 動画, 画像">
    <meta name="description" content="QOLONY（コロニー）はスキマ時間も休日も、「面白さ」＋「遊び心」をあなたに届けます。クイズや診断をみんなでシェアする、読み物を超えたエンタメマガジンです">
    <link rel="shortcut icon" href="https://s3-ap-northeast-1.amazonaws.com/qolony/images/service/favicon32.png" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    "admin/application" %>
    <%= javascript_include_tag "admin/application" %>
    <%= csrf_meta_tags %>


    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

  <section id="container" >
  <!--header start-->
  <header class="header fixed-top clearfix">
  <!--logo start-->
  <div class="brand">
      <div class="sidebar-toggle-box">
          <div class="fa fa-bars"></div>
      </div>
  </div>
  <!--logo end-->

  <div class="nav notify-row" id="top_menu">
      <!--  notification start -->
      <ul class="nav top-menu">
      </ul>
      <!--  notification end -->
  </div>
  <div class="top-nav clearfix">
      <!--search & user info start-->
      <ul class="nav pull-right top-menu">
          <li>
              <input type="text" class="form-control search" placeholder="検索まだできないよ">
          </li>
          <!-- user login dropdown start-->
          <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <img alt="" src="https://pbs.twimg.com/profile_images/378800000671725557/d1328b6b332c670047e35e064a36992a_normal.jpeg">
                  <span class="username"><%= current_user.email %></span>
                  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu extended logout">
                  <!-- <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li> -->
                  <!-- <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li> -->
                  <li>
                    <%= link_to logout_path do %>
                      <i class="fa fa-key"></i> Log Out</a>
                    <% end %>
                  </li>

              </ul>
          </li>
          <!-- user login dropdown end -->
      </ul>
      <!--search & user info end-->
  </div>
  </header>
  <!--header end-->
  <aside>
      <div id="sidebar" class="nav-collapse">
          <!-- sidebar menu start-->            <div class="leftside-navigation">
              <ul class="sidebar-menu" id="nav-accordion">
            <% if current_user.admin? || current_user.editor? %>
              <li class="sub-menu">
                <a href="javascript:;">
                  <i class="fa fa-bullhorn"></i>
                  <span>記事一覧</span>
                </a>
                <ul class="sub">
                  <li><%= link_to "記事案", draft_admin_articles_path %></li>
                  <li><%= link_to "画像挿入待ち記事", without_image_admin_articles_path %></li>
                  <li><%= link_to "予約投稿記事", future_admin_articles_path %></li>
                  <li><%= link_to "完成済み", completion_admin_articles_path %></li>
                  <li><%= link_to "公開記事", publish_admin_articles_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to admin_lists_path do %>
                  <i class="fa fa-tasks"></i>
                  <span>記事案リスト管理</span>
                <% end %>
              </li>
              <li>
                <%= link_to admin_users_path do %>
                  <i class="fa fa-user"></i>
                  <span>ライター一覧</span>
                <% end %>
              </li>
            <% end %>
              <li>
                <%= link_to user_admin_articles_path(user_id: current_user.id) do %>
                  <i class="fa fa-tasks"></i>
                  <span>あなたの記事一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to admin_youtubes_path do %>
                  <i class="fa fa-bullhorn"></i>
                  <span>Youtube動画投稿</span>
                <% end %>
              </li>
              <li>
                <%= link_to idea_admin_lists_path do %>
                  <i class="fa fa-th"></i>
                  <span>記事案リスト</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_admin_article_path do %>
                  <i class="fa fa-plus"></i>
                  <span>記事を書く</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_admin_video_path do %>
                  <i class="fa fa-plus"></i>
                  <span>動画を投稿</span>
                <% end %>
              </li>
          </ul></div>
  <!-- sidebar menu end-->
      </div>
  </aside>
<!--sidebar end-->

<!--main content start-->
  <section id="main-content">
    <section class="wrapper">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
        <%= yield %>
    </section>
  </section>
<!--main content end-->

  </section>
</body>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-env="<%= Rails.env %>">
  <link href='http://fonts.googleapis.com/css?family=Quicksand:700' id='gwebfont' type='text/css'>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- <meta name="viewport" content="width=device-width"> -->
  <title><%= full_title(yield(:title)) %></title>
  <meta name="keywords" content="QOLONY, コロニー, qolony, クイズ, 診断, キュレーション, まとめ, 動画, 画像">
  <meta name="description" content="<%= full_description(yield(:description)) %>">
  <link rel="shortcut icon" href="https://s3-ap-northeast-1.amazonaws.com/qolony/images/service/favicon32.png" >

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@qolony0">
  <meta name="twitter:creator" content="@qolony0">
  <meta name="twitter:title" content="<%= full_title(yield(:title)) %>">
  <meta name="twitter:description" content="<%= full_description(yield(:description)) %>">
  <meta name="twitter:image" content="<%= og_image(yield(:image)) %>">

  <meta property="fb:app_id" content="465680123608785">
  <meta property="fb:admins" content="100004127621540" />

  <meta property="og:title" content="<%= full_title(yield(:title)) %>">
  <meta property="og:description" content="<%= full_description(yield(:description)) %>">
  <meta property="og:url" content="<%= og_url(yield(:url)) %>">
  <meta property="og:image" content="<%= og_image(yield(:image)) %>">
  <meta property="og:site_name" content="qolony">


  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="https://media.twiliocdn.com/taskrouter/js/v1.1.1/taskrouter.min.js"></script>
</head>
<body class="<%= params[:controller] %>">
  <div id="container" class="max_height">
    <div id="root" class="max_height"></div>
    <%= yield %>
  </div>

  <%= include_gon %>
  <%= javascript_include_tag "client/app/application" %>
</body>
</html>

app/views/layouts/before_application.html.erb
<!DOCTYPE html>
<html ng-app ="qolony">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- <meta name="viewport" content="width=device-width"> -->
  <title>Telott(コロニー) トップページ</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
    <!-- 管理画面(userに見せないページ) -->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/debug.html.erb
<!DOCTYPE html>
<html data-env="<%= Rails.env %>" data-domless="<%= javascript_url "worker/application" %>">
  <link href='http://fonts.googleapis.com/css?family=Quicksand:700' id='gwebfont' type='text/css'>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- <meta name="viewport" content="width=device-width"> -->
  <title><%= full_title(yield(:title)) %></title>
  <meta name="keywords" content="QOLONY, コロニー, qolony, クイズ, 診断, キュレーション, まとめ, 動画, 画像">
  <meta name="description" content="<%= full_description(yield(:description)) %>">
  <link rel="shortcut icon" href="https://s3-ap-northeast-1.amazonaws.com/qolony/images/service/favicon32.png" >

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@qolony0">
  <meta name="twitter:creator" content="@qolony0">
  <meta name="twitter:title" content="<%= full_title(yield(:title)) %>">
  <meta name="twitter:description" content="<%= full_description(yield(:description)) %>">
  <meta name="twitter:image" content="<%= og_image(yield(:image)) %>">

  <meta property="fb:app_id" content="465680123608785">
  <meta property="fb:admins" content="100004127621540" />

  <meta property="og:title" content="<%= full_title(yield(:title)) %>">
  <meta property="og:description" content="<%= full_description(yield(:description)) %>">
  <meta property="og:url" content="<%= og_url(yield(:url)) %>">
  <meta property="og:image" content="<%= og_image(yield(:image)) %>">
  <meta property="og:site_name" content="QOLONY">


  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag "debug/application" %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <div id="qolony-client"></div>
    <div id="fb-root"></div>
    <%= yield %>
  </div>

  <%= include_gon %>
  <%= javascript_include_tag "application" %>
  <script>
    (function () {
      var media = window.matchMedia("(min-width: 769px)")
      if(media.matches) {
        var webfonts = document.getElementById('gwebfont');
        webfonts.rel = "stylesheet";
      }
    })();

  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-64819776-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- <meta name="viewport" content="width=device-width"> -->
  <title>QOLONY</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="loginページ">
    <meta name="author" content="Taishi">

    <title>コールセンターアプリ</title>


    <%= stylesheet_link_tag    "admin/application" %>
    <%= javascript_include_tag "admin/application" %>
    <%= csrf_meta_tags %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

    <%= yield %>

</html>

app/views/layouts/settings.html.erb
<!DOCTYPE html>
<html data-env="<%= Rails.env %>" data-domless="<%= worker_url "worker/application" %>">
  <link href='http://fonts.googleapis.com/css?family=Quicksand:700' id='gwebfont' type='text/css'>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- <meta name="viewport" content="width=device-width"> -->
  <title><%= full_title(yield(:title)) %></title>
  <meta name="keywords" content="QOLONY, コロニー, qolony, クイズ, 診断, キュレーション, まとめ, 動画, 画像">
  <meta name="description" content="<%= full_description(yield(:description)) %>">
  <link rel="shortcut icon" href="https://s3-ap-northeast-1.amazonaws.com/qolony/images/service/favicon32.png" >


  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container" class="max_height">
    <%= yield %>
  </div>

  <%= javascript_include_tag "admin/application" %>
</body>
</html>